using EscrevendoCelular.ConsoleApp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;

namespace TestEscreve
{
    [TestClass]
    public class UnitTest1
    {
        Escreve texto = new Escreve();

        [TestMethod]
        public void Test1()
        {
            Assert.AreEqual("77773367_7773302_222337777_777766606660366656667889999_9999555337777", texto.VerificaTexto("SEMPRE ACESSO O DOJOPUZZLES"));
        }

        [TestMethod] // o erro está certo
        public void Test255()
        {
            Assert.AreEqual("Sistema não suporta mais do que 255 caracteres", texto.VerificaTexto("SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLESSEMPRE ACESSO O DOJOPUZZLESSEMPRE ACESSO O DOJOPUZZLESSEMPRE ACESSO O DOJOPUZZLESSEMPRE ACESSO O DOJOPUZZLESSEMPRE ACESSO O DOJOPUZZLESSEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLES SEMPRE ACESSO O DOJOPUZZLESSEMPRE ACESSO O DOJOPUZZLES "));
        }
    }
}
